---
output: html_document
---

<- precompile this document with  ->
<- knitr::knit("vignettes/baseline_tables_stata.Rmd.orig", output = "vignettes/baseline_tables_stata.Rmd") ->




```stata
sysuse auto2
btable mpg weight displacement, by(foreign) saving("btab")
btable_format using "btab", clear
export delimited "formatted_btab.csv", replace novarnames
```

```
## 
## 
## . sysuse au(1978 automobile data)
## 
## . btable mpg weight displacement, by(foreign) saving("btab")
## file btab.dta saved
## 
## . btable_format using "btab", clear
## 
## . export delimited "formatted_btab.csv", replace novarnames
## file formatted_btab.csv saved
```

Then the table can be read back into R and printed with e.g. flextable.


```r
dat <- readr::read_csv("formatted_btab.csv")
```

```
## Warning: Missing column names filled in: 'X1' [1]
```

```r
dat[is.na(dat)] <- "" # replace NAs
names(dat)[1] <- " "  # set missing var name
dat %>%
  flextable::flextable()
```


<div class="tabwid"><style>.cl-ed2ad6b2{border-collapse:collapse;}.cl-ed233aba{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ed233abb{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-ed238a1a{width:54pt;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ed238a1b{width:54pt;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ed238a1c{width:54pt;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-ed2ad6b2'><thead><tr style="overflow-wrap:break-word;"><td class="cl-ed238a1c"><p class="cl-ed233abb"><span class="cl-ed233aba"> </span></p></td><td class="cl-ed238a1c"><p class="cl-ed233abb"><span class="cl-ed233aba">Total (N = 74)</span></p></td><td class="cl-ed238a1c"><p class="cl-ed233abb"><span class="cl-ed233aba">Domestic (N = 52)</span></p></td><td class="cl-ed238a1c"><p class="cl-ed233abb"><span class="cl-ed233aba">Foreign (N = 22)</span></p></td><td class="cl-ed238a1c"><p class="cl-ed233abb"><span class="cl-ed233aba">Mean difference (95% CI)</span></p></td><td class="cl-ed238a1c"><p class="cl-ed233abb"><span class="cl-ed233aba">P-value</span></p></td><td class="cl-ed238a1c"><p class="cl-ed233abb"><span class="cl-ed233aba">Descriptives</span></p></td><td class="cl-ed238a1c"><p class="cl-ed233abb"><span class="cl-ed233aba">Effects</span></p></td><td class="cl-ed238a1c"><p class="cl-ed233abb"><span class="cl-ed233aba">Tests</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba"></span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">mean (sd)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">mean (sd)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">mean (sd)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba"></span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba"></span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba"></span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba"></span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">Mileage (mpg)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">21 (5.8)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">20 (4.7)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">25 (6.6)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">-4.9 (-7.7 - -2.2)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">&lt;0.001</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">mean (sd)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">mean difference (95% CI)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">Student's t-test</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">Weight (lbs.)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">3019 (777)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">3317 (695)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">2316 (433)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">1001 (682 - 1321)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">&lt;0.001</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">mean (sd)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">mean difference (95% CI)</span></p></td><td class="cl-ed238a1a"><p class="cl-ed233abb"><span class="cl-ed233aba">Student's t-test</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ed238a1b"><p class="cl-ed233abb"><span class="cl-ed233aba">Displacement (cu. in.)</span></p></td><td class="cl-ed238a1b"><p class="cl-ed233abb"><span class="cl-ed233aba">197 (92)</span></p></td><td class="cl-ed238a1b"><p class="cl-ed233abb"><span class="cl-ed233aba">234 (85)</span></p></td><td class="cl-ed238a1b"><p class="cl-ed233abb"><span class="cl-ed233aba">111 (25)</span></p></td><td class="cl-ed238a1b"><p class="cl-ed233abb"><span class="cl-ed233aba">122 (85 - 159)</span></p></td><td class="cl-ed238a1b"><p class="cl-ed233abb"><span class="cl-ed233aba">&lt;0.001</span></p></td><td class="cl-ed238a1b"><p class="cl-ed233abb"><span class="cl-ed233aba">mean (sd)</span></p></td><td class="cl-ed238a1b"><p class="cl-ed233abb"><span class="cl-ed233aba">mean difference (95% CI)</span></p></td><td class="cl-ed238a1b"><p class="cl-ed233abb"><span class="cl-ed233aba">Student's t-test</span></p></td></tr></tbody></table></div>

