# This function showcases how one might write a function to be used as an
# RStudio project template. This function will be called when the user invokes
# the New Project wizard using the project template defined in the template file
# at:
#
#   inst/rstudio/templates/project/hello_world.dcf
#
# The function itself just echos its inputs and outputs to a file called INDEX,
# which is then opened by RStudio when the new project is opened.
CTUtemplate <- function(path, ...) {

  require(glue)

  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)


  # collect inputs
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
    # assign(key, val, envir = parent.frame())
  })


  # create new folders
  folderend <- ifelse(dots$folderEnd == "_xx", "_xx", paste0("_", dots$projNum))

  folders <- c(od =  glue("01_Original_data{folderend}"),
               sa =  glue("02_1_Stata_ado{folderend}"),
               ss =  glue("02_2_Stata_scripts{folderend}"),
               rs =  glue("03_R_scripts{folderend}"),
               pd =  glue("04_prepared_data{folderend}"),
               fd =  glue("05_Figures{folderend}"),
               td =  glue("06_Tables{folderend}"),
               ld =  glue("07_Log_files{folderend}"),
               rd =  glue("08_Reports{folderend}"),
               qc =  glue("09_QualityControl{folderend}"),
               pub = glue("10_Publication{folderend}"))

  lapply(file.path(path, folders), dir.create, showWarnings = FALSE)

  # generate header
  header <- c(
    "# This file was generated by a call to 'CTUtemplate::CTUtemplate()'.",
    "# The following inputs were received:",
    ""
  )

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    paste(folders, collapse = "\n"),
    sep = "\n", collapse = "\n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "INDEX"))

  # header
  header <- function(projNum, projName, au, purpose, short = TRUE, R = TRUE){
    date <- Sys.Date()
    lines <- list()
    lines[[2]] <- "# This file was generated by a call to 'CTUtemplate::CTUtemplate()'."
    lines[[3]] <- glue("Study:{projNum} {projName}")
    lines[[4]] <- glue("Purpose: {purpose}", )
    lines[[5]] <- glue("Author: {au}")
    lines[[6]] <- glue("Date created: {date}")
    lines[[7]] <- "Last update:"
    if(!short){
      lines[[8]] <- "Date of database export:"
      lines[[9]] <- "Underlying SAP version:"
      lines[[10]] <- "Underlying Study Protocol version:"
    }
    lines <- stringr::str_pad(lines, max(nchar(lines)), "right")
    lines[[1]] <- stringr::str_pad("", max(nchar(lines)), pad = "*")
    lines[[length(lines)+1]] <- lines[[1]]
    if(R) lines <- paste("# /*", lines, "*/")
    paste(paste(lines, collapse = "\n"), "\n\n\n")
  }


  # R ----
  # masterfile
  paths <- mapply(function(x, y){
    x <- function(...) file.path(path, y, ...)
  }, names(folders), folders)

  contents <- paste(header(dots$projNum,
                           dots$projName,
                           dots$au,
                           "MASTERFILE",
                           short = FALSE),
                    'options(stringsAsFactors = FALSE)\n',
                    glue('pp <- here::here() # change if necessary'),
                    "setwd(pp)", "",
                    paste0('paths <- mapply(function(x, y){
                    x <- function(...) file.path(pp, y, ...)
                    },
                    c("', paste0(names(folders), collapse = '", "'),'"),\n',
                    'c("', paste0(folders, collapse = '", \n"'),
                    '"))'),
                    'source(paths$rs("01_packages_funs.R"))',
                    'source(paths$rs("02_dataprep.R"))',
                    'source(paths$rs("03_baseline.R"))',
                    'source(paths$rs("04_analysis.R"))\n\n',
                    '# package control through renv ----',
                    '# initialize',
                    '# renv::init() # just needed once',
                    '# save a snapshot of packages and versions',
                    '# renv::snapshot() # occasionally (e.g. when finalizing a report)',
                    '# restore versions in current lockfile',
                    '# renv::restore() # e.g. if something broke after updating package(s)',
                    sep = "\n")
  writeLines(contents, con = paths$rs("00_MASTERFILE.R"))

  # packages
  contents <- paste(header(dots$projNum,
                           dots$projName,
                           dots$au,
                           "Load necessary packages",
                           short = TRUE),
                    "\n\n\n",
                    "# Load packages",
                    'library("atable")',
                    'atable_options(format_to = "console", add_margins = TRUE)\n',
                    'library("tidyverse")',
                    'library("here")',
                    'library("renv")',
                    'library("Hmisc")',
                    "\n\n",
                    "# custom functions",
                    'mykeep <- function(...){
     gdata::keep(paths, pp, mykeep, ..., sure = TRUE)
  }',
                    sep = "\n")
  writeLines(contents, con = paths$rs("01_packages_funs.R"))

  # data prep
  contents <- paste(header(dots$projNum,
                           dots$projName,
                           dots$au,
                           "Data preparation",
                           short = TRUE),
                    "\n\n\n",
                    '# Load data',
                    'raw <- read.csv(paths$od("data.csv"))',
                    '# apply labels (Hmisc::label is compatible with atable)',
                    'label(raw$var1) <- "Label of var1"',
                    '# save prepped data',
                    'saveRDS(prepped_data, paths$pd("prepped_data"))',
                    '# clear the working space\nmykeep()',
                    sep = "\n")
  writeLines(contents, con = paths$rs("02_dataprep.R"))

  # baseline
  contents <- paste(header(dots$projNum,
                           dots$projName,
                           dots$au,
                           "Baseline Tables",
                           short = TRUE),
                    "\n\n\n",
                    '# Load data ----',
                    'dat <- readRDS(paths$pd("prepped_data"))',
                    '# make baseline table ----',
                    'tab <- atable(dat, target_vars = c("var1", "var2"), group_col = "grp_var")',
                    'write.csv(tab, paths$td("baselineTable.csv))',
                    'mykeep()',
                    sep = "\n")
  writeLines(contents, con = paths$rs("03_baseline.R"))

  # analysis
  contents <- paste(header(dots$projNum,
                           dots$projName,
                           dots$au,
                           "Main analysis",
                           short = TRUE),
                    "\n\n\n",
                    '# Load data',
                    'dat <- readRDS(paths$pd("prepped_data"))',
                    'mod <- lm(var1 ~ grp_var, dat)',
                    '# etc',
                    'mykeep()',
                    sep = "\n")
  writeLines(contents, con = paths$rs("04_analysis.R"))



  # blank
  contents <- paste(header(dots$projNum,
                           dots$projName,
                           dots$au,
                           "XXXXX",
                           short = TRUE),
                    "\n\n\n",

                    sep = "\n")
  writeLines(contents, con = paths$rs("xx_template.R"))

}

# funs <- mapply(function(x, y){
#   assign(x, function(z) file.path(path, y, z))
# },
# c("od", "fd", "td", "ld", "rd", "sd"), c("", ""))


